spring:
    profiles:
        active:
        -  dev
---
spring:
    profiles: dev      #开发环境
    application:
        name: microservicecloud-config-liujunhong-dev
---
spring:
    profiles: test  #test 测试环境
    application:
        name: microservicecloud-config-liujunhong-test
#一定要以 utf8 格式保存

